apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresdb-config
data:
  POSTGRES_DB: postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresdb-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # Remplacez cette valeur par votre utilisateur codé en base64
  POSTGRES_PW: cmVjb21tZW5kYXRpb25fZmlsbXNfb2N0XzIzX01MT1BT

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  storageClassName: manual
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"
    type: DirectoryOrCreate

---

# persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres-db
  serviceName: "postgresdb-movieflix"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "manual"
      resources:
        requests:
          storage: 7Gi

---

apiVersion: v1
kind: Service
metadata:
  name: postgresdb-movieflix
spec:
  type: LoadBalancer
  ports:
    - port: 5431
      targetPort: 5432
  selector:
    app: postgresdb-movieflix
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresdb-init-job
spec:
  template:
    spec:
      containers:
      - name: init-db
        image: recofilmsmlopsoct2023/movieflix-initdb:latest
        envFrom:
          - configMapRef:
              name: postgresdb-config
          - secretRef:
              name: postgresdb-secret
        env:
          - name: POSTGRES_HOST
            value: postgresdb-movieflix
          - name: POSTGRES_PORT
            value: "5431"
      restartPolicy: Never
  backoffLimit: 4

