apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresdb-config
data:
  POSTGRES_DB: postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresdb-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # Remplacez cette valeur par votre utilisateur codé en base64
  POSTGRES_PASSWORD: cmVjb21tZW5kYXRpb25fZmlsbXNfb2N0XzIzX01MT1BT

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  storageClassName: hostpath
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"
    type: DirectoryOrCreate

---

# persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
spec:
  selector:
    matchLabels:
      app: postgresdb-movieflix
  serviceName: "postgresdb-movieflix"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresdb-movieflix
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgresdb-config
        - secretRef:
            name: postgresdb-secret
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: hostpath
      resources:
        requests:
          storage: 7Gi

---

apiVersion: v1
kind: Service
metadata:
  name: postgresdb-movieflix
spec:
  type: LoadBalancer
  ports:
    - port: 5431
      targetPort: 5432
  selector:
    app: postgresdb-movieflix

---

apiVersion: v1
kind: Pod
metadata:
  name: postgresdb-init-pod
spec:
  containers:
  - name: init-db
    image: recofilmsmlopsoct2023/movieflix-initdb:latest
    envFrom:
      - configMapRef:
          name: postgresdb-config
      - secretRef:
          name: postgresdb-secret
    env:
      - name: POSTGRES_HOST
        value: postgresdb-movieflix
      - name: POSTGRES_PORT
        value: "5431"
      - name: PYTHONUNBUFFERED
        value: "1"
  restartPolicy: Never