{
 "title": "MovieFlix Dash",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Taux de requete sur 24h",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance)(rate(http_requests_total{job='movieflix-api'}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de requete HTTP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total) ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Taille moyenne(octets) de reponses HTTP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_response_size_bytes_sum[2h])) / sum(rate(http_response_size_bytes_count\n[2h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux moyen de requêtes par seconde 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[20m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux d'erreur 5XX/4XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total{status=~\"^(5..|4..)$\"}[20m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durée moyenne de requête sur 1h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1h])) / sum(rate(http_request_duration_seconds_count[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}