# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI-CD-TEST-DATABASE

on:
  push:
    branches: [ "create_database"]
  pull_request:
    branches: [ "create_database" ]

permissions:
  contents: read

jobs:
  build-cd:

    runs-on: ubuntu-latest
    env:
      DBNAME: ${{ secrets.DBNAME }}
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}
      HOST: localhost
      PORT: ${{ secrets.PORT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRATION: ${{ secrets.ACCESS_TOKEN_EXPIRATION }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    steps:
    - uses: actions/checkout@v3
      name: Chekout
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        if [ -f ./src/api/requirements.txt ]; then pip install -r ./src/api/requirements.txt; fi
    - name: Lancer base de donnée local
      uses: hoverkraft-tech/compose-action@v1.5.1
      with:
        compose-file: "./database/test/docker-compose.yaml"
      env:
        POSTGRES_USER: postgres
        POSTGRES_PW: recommendation_films_oct_23_MLOPS
        POSTGRES_DB: postgres
    - name : Insert data
      run: |
        python3 ./database/test/create_database.py
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest